name: Node.js CI/CD

on:
  push:
    branches:
      - main
      - Feature/AzureSetup

jobs:
  jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build
        run: |
          echo "Building the project"
          # your build command here

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/Feature/AzureSetup'
    steps:
      - name: Deploy
        run: |
          echo "Deploying the project"
          # your deploy command here
      
      - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: './public'  # Ensure this matches your output directory as defined in webpack.config.js